FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY OsApi/OsApi.csproj OsApi/OsApi.csproj
RUN dotnet restore "OsApi/OsApi.csproj"

COPY . .

WORKDIR /src/OsApi
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS run
WORKDIR /app

RUN mkdir -p /app/wwwroot/uploads

COPY --from=build /app ./

EXPOSE 5000
ENV ASPNETCORE_ENVIRONMENT=Development

ENTRYPOINT ["dotnet", "OsApi.dll"]