services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password --sql-mode=""
    ports: ["3306:3306"]
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    ports: ["8080:8080"]
    depends_on: [mysql]

  api:
    build:
      context: ./api
      target: build
    working_dir: /src/OsApi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
      ASPNETCORE_URLS: http://+:${API_PORT}
      ConnectionStrings__Default: "server=mysql;port=3306;database=${MYSQL_DATABASE};user=${MYSQL_USER};password=${MYSQL_PASSWORD};TreatTinyAsBoolean=true"
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: osapi
      Jwt__Audience: osweb
    ports: ["${API_PORT}:${API_PORT}"]
    volumes:
      - ./api:/src
      - ./uploads:/src/OsApi/wwwroot/uploads
    command: >
      bash -lc "dotnet restore &&
                dotnet watch run --no-launch-profile --urls=http://0.0.0.0:${API_PORT}"
    depends_on: [mysql]

  web:
    build: ./web
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "1"
      VITE_API_BASE: "http://localhost:${API_PORT}"
    command: npm run dev -- --host 0.0.0.0
    ports: ["${WEB_PORT}:5173"]
    depends_on: [api]

volumes:
  mysql_data:
